FROM alpine

RUN apk update && \
    apk upgrade && \ 
    apk add python py-pip g++ python-dev linux-headers

ADD . /seabus

RUN pip install -r /seabus/seabus/requirements.txt && \
    apk del g++ python-dev linux-headers

WORKDIR /seabus

CMD python manage.py listendev
