FROM amancevice/pandas:core-python2
RUN pip install pandas==0.19.0

ADD . /seabus

RUN \
 apk update && \
 apk add linux-headers && \
 pip install -r /seabus/seabus/requirements.txt

EXPOSE 5000
WORKDIR /seabus/
CMD ["uwsgi", "--http", ":5000", "--gevent", "1000", "--http-websockets", "--master", "--wsgi-file", "wsgi.py", "--callable", "app"]
